### ISSUE TITLE
[Bug] Files with .opml extension are unavailable for import

### ISSUE THREAD

**Issue by mikhirev** [readrops/Readrops#201] opened 2024-09-17 08:56 UTC
**Describe the bug**
I tried to import a file with `.opml` name extension, however it was impossible to select it. I had to change the extension to `.xml`, after that it was imported successfully.

**To Reproduce**
1. Create an OPML file with `.opml` extension, e. g. export it from Flym.
2. Try to import this file to Readrops.
3. File is grayed and unavailable for selection.

**Expected behavior**
File can be selected and imported.

**Environment information (please complete the following information):**
 - App version: 2.0-beta02
 - Android version: GrapheneOS 13
 - Device type: Pixel 4a

**Comment by Shinokuni** [comment] 2024-09-17 10:28
Duplicate of #195. Fixed in 2.0.

**Closed by Shinokuni** 2024-09-17 10:28 UTC
