### ISSUE TITLE
Login fails with nextcloud news

### ISSUE THREAD

**Issue by stop5** [readrops/Readrops#42] opened 2020-01-24 15:59 UTC
When i try to login with my username, logintoken and my nextcloud url i get the following error:
onSuccess called with null. Null Values are generally not allowed in 2.x operators and sources. 

I use version 1.1.1 on Android 8.1.

**Comment by Shinokuni** [comment] 2020-01-25 16:55
I definitely need to improve error messages. But this message says that the login failed. Please check your Nextcloud URL and your credentials. Also, if you entered a bad URL, you will have to close and reopen the activity (bug recently fixed).

Finally, please check you don't have the Nextcloud Two-Factor TOTP Provider app activated as it can break Nextcloud News authentication.

**Comment by doronbehar** [comment] 2020-01-30 08:01
I'm encountering the same error and I have 2 factor authentication enabled so I used an app password - a password that looks like this:

`XXXXX-XXXXX-XXXXX-XXXXX-XXXXX`

Also, I'm using nextcloud version 18.0.0 - https://github.com/nextcloud/server/releases/tag/v18.0.0

**Comment by Shinokuni** [comment] 2020-02-01 19:51
I don't think I can do much more for you. We should have the Nextcloud News team aware of this issue.

I will do some others auth tests, but currently, if you want to use News API, you will have to disable 2-FA.

**Comment by rtyler** [comment] 2020-02-09 20:44
For what it's worth, I was just able to login with an app password using 17.0.1

**Comment by doronbehar** [comment] 2020-02-10 14:28
I've probably had something confused with my passwords :) Can confirm this works with the latest version on F-Droid.

**Comment by Shinokuni** [comment] 2020-02-10 15:05
So maybe they have fixed this :thinking:, and the issue is elsewhere. Thanks both for you feedback!

**Comment by Shinokuni** [comment] 2020-07-19 13:26
Is there still something wrong here or can I close this issue?

**Closed** 2020-07-24 17:57 UTC
