### ISSUE TITLE
Gesture or button to jump to next unread message

### ISSUE THREAD

**Issue by ddeimeke** [readrops/Readrops#159] opened 2022-05-02 10:11 UTC
Hi!

I am a pretty heavy feed user, using FreshRSS on the server side.

Would it be possible to have a shortcut to jump to the next unread article while viewing an article. Currently I have to leave the article to the overview and choose the next one to read.

Thanks a lot!

Cheers

Dirk

**Comment by csolisr** [comment] 2022-06-06 14:30
Same here, I use Nextcloud News but can also self-host TTRSS or FreshRSS to test. The main reason why I can't use this app as my main RSS reading application is the fact that I need to manually go back a page and manually select the next news article, that greatly diminishes my reading speed in comparison to most other mobile apps for Nextcloud News specifically. What would be the most appropriate way to handle going to the next article though, a swipe to the right or a dedicated set of next/previous buttons on the header? Or potentially both? I'm not sure if the library you use for displaying the article handles swipes, so a set of buttons would be an acceptable compromise.

**Comment by mdbdb** [comment] 2022-06-12 06:28
I'm testing readrops right now and the point is the first one I noticed. It would be great if there were both options: Buttons to go to the next or previous article as well as swipe right or left.

**Comment by WhiteNight121** [comment] 2022-10-05 12:48
Hello, I'm trying to move away from Feedly but swiping to the next article is one of the main features I'm looking for I tried just about all the app options for Android from the freshRSS site and none of them seem to be able to do this.

I would be willing to donate money to get this done so that I can get off of Feedly.

Thanks for everything you do.

**Comment by Shinokuni** [comment] 2024-09-07 16:51
Duplicate of #62.

**Closed by Shinokuni** 2024-09-07 16:51 UTC
