### ISSUE TITLE
Feature request: Long press menu for links in a feed

### ISSUE THREAD

**Issue by tactical-snail** [readrops/Readrops#150] opened 2022-02-05 08:56 UTC
Long pressing website links, or a word containing link in a feed, in the app's default reader should open a menu with the url on the top and open link, copy link, share link options.
This would be helpful as you can view the url before opening it or open it in a different browser using the share/copy button.

**Comment by Shinokuni** [comment] 2024-09-07 17:14
Actually duplicate of #111.

**Closed by Shinokuni** 2024-09-07 17:14 UTC
Labels: enhancement
