### ISSUE TITLE
"Open items in" setting has no effect

### ISSUE THREAD

**Issue by keunes** [readrops/Readrops#95] opened 2021-01-01 07:31 UTC
Hello

In my exploration of the app, I poked around in the settings, including the 'Open items in' setting. I switched it between 'External navigator' and 'Webview', but don't notice a change.

From the article list items always open in the app (as I'd expect), hitting the 'Open in browser' button always opens my default browser (I guess also as expected).

Thanks!

**Comment by Shinokuni** [comment] 2021-01-01 17:18
I will take a look, thanks.

**Comment by keunes** [comment] 2021-01-02 09:50
(Not sure btw what 'Webview' means, maybe it's behaving as expected.)

**Comment by Shinokuni** [comment] 2021-07-16 15:55
I'm not able to reproduce, which account do you use?

With the "Open in webview" option, you aren't supposed to quit Readrops. The web page will be displayed in a new screen but not in an external navigator.

**Comment by Shinokuni** [comment] 2024-09-15 14:40
This should be fixed in the new [2.0 version](https://github.com/readrops/Readrops/releases) as the UI has been entirely remade.

**Closed by Shinokuni** 2024-09-15 14:40 UTC
Labels: bug, 2.0
