### ISSUE TITLE
[Bug] Shortcut to open article with webview requires several click to work

### ISSUE THREAD

**Issue by GLLM** [readrops/Readrops#113] opened 2021-07-26 17:57 UTC
Hi !
When reading an article, I need to click several times (3-4 most times) on the icon to open them in a webview ... it just does not work the first click most times.

![image](https://user-images.githubusercontent.com/3989573/127036716-a9c48fbc-fe93-44ec-a9a1-81eae2c16d16.png)

I have
* Samsung S8+
* Android 9
* Readrop 1.3 with FreshRSS v1.18.1

Thanks
GLLM

**Comment by Shinokuni** [comment] 2021-08-18 17:40
I am not able to reproduce. The menu button is a standard Android component and I didn't tweak it. Your top bar doesn't seems to be really small either.

Do you have a really small screen?

**Comment by GLLM** [comment] 2021-08-29 14:51
I'm not sure how to provide more details  :-(

Indeed, my bar is not small, so it's not a matter of reaching it or touching the right part of the bar.
But clearly, there's a bug. At least on my side/phone. The button requires 2/3 clicks to do something.

2 things I've noted, maybe it can be of help : 
- For the back menu button (top left arrow, going left), when a click is registered, the button gets a grey circle appearing very shortly, showing the click on the menu has been performed. I DOT NOT get such visual cue when I click on the "Open in rborwser" or "Share" menu.
- when I long press the open browser button or the share button, i do not get a hint shown to explain what this menu is meant to do. It such help hint expected ?

**Comment by bhiemenz** [comment] 2021-09-26 11:12
I have the same issue.

I have
* Fairphone 3
* Android 10
* Readrop 1.3 with FreshRSS v1.19.0-dev

Not sure why it happens from time to time. Unfortunately, I also do not know which further details can help here.

**Comment by dbolton** [comment] 2022-05-15 02:33
I also have this issue (Samsung S10, Android 12, Readrop 1.3.1).

Does the clickable area include the surrounding blue or is it just the white icon that is clickable?

**Comment by Shinokuni** [comment] 2024-09-15 14:40
This should be fixed in the new [2.0 version](https://github.com/readrops/Readrops/releases) as the UI has been entirely remade.

**Closed by Shinokuni** 2024-09-15 14:40 UTC
Labels: question, 2.0
