### ISSUE TITLE
[Bug] settings lost after closing the app

### ISSUE THREAD

**Issue by SSintermann** [readrops/Readrops#207] opened 2024-09-19 20:40 UTC
**Describe the bug**

**To Reproduce**
1. Set hide read items in filter
2. Close settings
3. Force close app
4. Restart app
5. Read items displayed

**Expected behavior**
Filter settings should be kept

**Environment information (please complete the following information):**
 - Account type: Freshrss
 - App version: 2.0 beta
 - Android version: 14
 - Device type: pixel8
 - Store: Play Store

**Additional context**

**Comment by Shinokuni** [comment] 2024-09-20 09:22
Duplicate of #138.

**Closed by Shinokuni** 2024-09-20 09:22 UTC
