### ISSUE TITLE
navigate between feeds

### ISSUE THREAD

**Issue by ABnSultan** [readrops/Readrops#171] opened 2023-06-14 19:50 UTC
how do you navigate to the next feed? there's no next button also tried swiping right and left and also checked setting and nothing is there

**Comment by Fale** [comment] 2024-03-02 09:04
Adding swiping ability would be awesome IMHO!

**Comment by Shinokuni** [comment] 2024-09-07 16:51
Duplicate of #62.

**Closed by Shinokuni** 2024-09-07 16:51 UTC
