### ISSUE TITLE
[Bug] Unreadable feed name in timeline

### ISSUE THREAD

**Issue by mikhirev** [readrops/Readrops#203] opened 2024-09-17 09:18 UTC
**Describe the bug**
When using the dark theme, some feed name are displayed in color that is extremely hard to read on the dark gray background. E. g. all feeds from livejournal.com have the same dark blue color.

**To Reproduce**
1. Set the dark theme.
2. Add any feed from livejournal.com.
3. Refresh the timeline.
4. The feed name is displayed in dark blue on the dark gray background that is very hard to read.

**Expected behavior**
All text in timeline is readable, no matter what theme you use.

**Environment information (please complete the following information):**
 - Account type: local
 - App version: 2.0-beta02
 - Android version: GrapheneOS 13
 - Device type: Pixel 4a

**Additional context**
Using the same color for different feeds from livejournal.com could also be considered a bug.

**Comment by Shinokuni** [comment] 2024-09-17 10:29
Duplicate of #172.

**Closed by Shinokuni** 2024-09-17 10:29 UTC
