### ISSUE TITLE
"Show read items" not saved on v2-beta2

### ISSUE THREAD

**Issue by yubiuser** [readrops/Readrops#198] opened 2024-09-15 11:30 UTC
I use to **uncheck** the filter setting " Show read items" on Android using v2-beta2. However, after a while when I reopen the app the setting is reverted to the default setting showing all items again.

**Comment by Shinokuni** [comment] 2024-09-15 11:52
Duplicate of #138.

**Closed by Shinokuni** 2024-09-15 11:52 UTC

**Comment by yubiuser** [comment] 2024-09-15 12:24
I didn't consider this old issue 'still valid'
