### ISSUE TITLE
Error when refreshing feed

### ISSUE THREAD

**Issue by macxcool** [readrops/Readrops#192] opened 2024-09-01 11:27 UTC
I'm using Readrops with a self-hosted, local FreshRSS instance. FDroid recently upgraded me to 2.0beta01 and now I can't launch Readrops without a crash. It crashes immediately.

**Comment by Shinokuni** [comment] 2024-09-04 10:06
I am going to need more infos if you want me to help you:
- Where does the error occurs? Did you get a crash screen with a stacktrace?
- Which account type?
- Which app version? beta or old stable?

**Comment by macxcool** [comment] 2024-09-04 11:36
Sorry. I just submitted automatically via the app. I didn't know that it wouldn't include anything useful. I'll get that for you.

**Comment by macxcool** [comment] 2024-09-04 11:48
I'm using Readrops with a self-hosted FreshRSS instance. It worked fine until FDroid upgraded me to 2.0beta01. I'm not sure why I got a beta version, but I upgraded to it and got the error. Here is the trace:
```
org.koin.core.error.InstanceCreationException: Could not create instance for '[Factory:'com.readrops.app.repositories.BaseRepository']'
at org.koin.core.instance.InstanceFactory.create(SourceFile:185)
at org.koin.core.instance.FactoryInstanceFactory.get(SourceFile:1)
at org.koin.core.scope.Scope.resolveInstance(SourceFile:109)
at org.koin.core.scope.Scope.get(SourceFile:127)
at androidx.paging.ChannelFlowCollector.emit(SourceFile:38)
at kotlinx.coroutines.flow.DistinctFlowImpl$collect$2.emit(SourceFile:763)
at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SourceFile:5)
at kotlinx.coroutines.flow.internal.SafeCollector.emit(SourceFile:10)
at kotlinx.coroutines.flow.internal.SafeCollector.emit(SourceFile:1)
at kotlinx.coroutines.flow.FlowKt.emitAllImpl$FlowKt__ChannelsKt(SourceFile:130)
at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(SourceFile:12)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
at kotlinx.coroutines.DispatchedTask.run(Unknown Source:96)
at androidx.work.Worker$2.run(SourceFile:32)
at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:96)
```

**Comment by macxcool** [comment] 2024-09-04 11:57
I had exactly the same thing happen on my Android phone and tablet, btw. It crashes immediately without showing me anything. Neither one is particularly new, though. The phone is Android 8 and the tablet 10.

I uninstalled on my tablet and then upgraded to the 2.0beta01 version. Now the app launches asking for an account. I'll find my FreshRSS credentials and see if it will connect after I re-add the account.

**Comment by macxcool** [comment] 2024-09-05 10:52
OK. Starting from scratch with a fresh install and entering my credentials _does_ work, but it still _did_ crash when I upgraded, which isn't good.

**Comment by macxcool** [comment] 2024-09-05 10:57
I've removed, reinstalled, and re-authenticated on my Android tablet, so _it's_ working now. I'll leave things broken on my phone for testing purposes, if needed.

**Comment by Shinokuni** [comment] 2024-09-05 12:36
Thanks for the infos! So it is a duplicate of #182. I submitted a few days ago a fix version to F-Droid. Could you try out when it's available?

**Comment by macxcool** [comment] 2024-09-05 13:56
I only see 2.0beta01 in FDroid still. I'll keep an eye out for an update.

**Comment by macxcool** [comment] 2024-09-10 17:57
OK. I upgraded Readrops on my phone to 2.0beta02 and the error has gone. It now loads my FreshRSS feed like normal. Thanks.

**Closed** 2024-09-10 22:45 UTC
Labels: bug, 2.0
