### ISSUE TITLE
[Feature] Allow to configure swipe

### ISSUE THREAD

**Issue by odolbeau** [readrops/Readrops#222] opened 2024-10-31 11:07 UTC
**Is your feature request related to a problem? Please describe.**
I "Lost" a few unread articles due to the high sensibility of the swipe left feature.

**Describe the solution you'd like**
Allow to configure which action should be take when swiping left. Could be "mark as read" by default to keep the existing behavior but could ne "nothing" for example.

**Describe alternatives you've considered**
Could be a link / button or something which can "cancel" the mark as read action.

**Additional context**

**Comment by Shinokuni** [comment] 2024-11-08 13:12
Duplicate of #117.

**Closed by Shinokuni** 2024-11-08 13:12 UTC
