### ISSUE TITLE
Fail to import OPML

### ISSUE THREAD

**Issue by linsui** [readrops/Readrops#41] opened 2020-01-24 12:01 UTC
I export an OPML file from flym but I can't import it in Readrops.

```xml
<?xml version="1.0" encoding="utf-8"?>
<opml version="2.0">
  <head>
    <dateCreated>Fri, 24 Jan 2020 11:47:47 GMT</dateCreated>
    <docs />
  </head>
  <body>
    <outline type="rss" title="Tech">
      <outline type="rss" title="Opensource.com" xmlUrl="https://opensource.com/feed" />
    </outline>
  </body>
</opml>
```

I got an error `Ordered element 'header' missing for class e.d.a.a.b.c`

**Comment by returntrip** [comment] 2020-01-24 12:54
Same for Nextxloud opmls

**Comment by Shinokuni** [comment] 2020-01-25 16:42
Thanks for the report, I will investigate.

**Comment by Shinokuni** [comment] 2020-01-25 20:16
So I forgot to add a proguard rule for OPML model. It was deleted in the release version as SimpleXML uses it by reflection. Fixed in 7ed5876285cda4661b94aee2fc708e6b3fb3d13d.

I am waiting for #42 before creating a release (if it doesn't take too much time).

**Comment by Shinokuni** [comment] 2020-01-30 21:56
A new release is available with the fix! It should be available in F-droid in a few days.

**Closed by Shinokuni** 2020-01-30 21:56 UTC
Labels: bug

**Comment by xantulon** [comment] 2020-02-15 15:35
Version 1.1.2(8) from F-Droid, OPML import gives "An error occurred during the file processing" when I try to import OPMLs from Nextcloud or Thunderbird.



[OPML_Examples.zip](https://github.com/readrops/Readrops/files/4208655/OPML_Examples.zip)

**Comment by Shinokuni** [comment] 2020-02-16 13:48
I can reproduce with the `MyThunderbirdFeeds-RSS` file. But it does come from the file which has a `</outline>` end tag in excess : 

`<outline type="rss" title="Weybec Studio" text="Weybec Studio" version="RSS" fz:quickMode="true" fz:options="{&quot;version&quot;:2,&quot;updates&quot;:{&quot;enabled&quot;:true,&quot;updateMinutes&quot;:100,&quot;updateUnits&quot;:&quot;min&quot;,&quot;lastUpdateTime&quot;:1581773067722,&quot;lastDownloadTime&quot;:1581105308174,&quot;updatePeriod&quot;:&quot;&quot;,&quot;updateFrequency&quot;:&quot;&quot;,&quot;updateBase&quot;:&quot;&quot;},&quot;category&quot;:{&quot;enabled&quot;:false,&quot;prefixEnabled&quot;:false,&quot;prefix&quot;:null}}" xmlUrl="https://www.youtube.com/feeds/videos.xml?channel_id=UCcV2VutsI6RTyz4uMrZVQmA" htmlUrl="http://www.youtube.com/feeds/videos.xml?channel_id=UCcV2VutsI6RTyz4uMrZVQmA"/></outline>
    </outline>`

See at the end. It is surprising to see this kind of issue from Thunderbird opml export.

The other file works but I don't get any result from syncing, which is weird as I can get information from the feeds (title, description...).

**Comment by Shinokuni** [comment] 2020-02-22 16:41
Some news of your OPML feeds @xantulon .

Firstly, Readrops doesn't have support for youtube feeds. I wasn't aware of the fact that youtube has it own RSS schema.

Secondly, vimeo feeds parsing works, but they provide a wrong feed url, for example `<atom:link rel="self" href="https://vimeo.com/erogenesis/videos/erogenesis/videos/rss"/>` instead of `<atom:link rel="self" href="https://vimeo.com/erogenesis/videos/rss"/>` which is quite annoying. I could add an exception for Vimeo but then I will have to do so for other feeds too which could make the code more complex.

**Comment by paulle** [comment] 2020-12-06 14:07
I can't import opml files. If I try to import, file shows in file manager, can select it and "import" it. But nothing.

**Comment by Shinokuni** [comment] 2020-12-12 18:46
Could you tell me which version of Readrops you are using and give me a sample of your opml file?

**Comment by paulle** [comment] 2020-12-12 19:24
I'm using v1.2.1.    android10  sony-xperia 5

I couldn't attach the opml file, because github don't this file type as an attachment.
So I opened it with an editor and put it here.

<?xml version="1.0" encoding="UTF-8"?>
<opml version="1.1">
  <head>
    <title>
      Feeder
    </title>
  </head>
  <body>
    <outline title="Zurückstellen" text="Zurückstellen" type="rss" xmlUrl="http://"/>
    <outline title="Panorama &amp; Wissen/Technik" text="Panorama &amp; Wissen/Technik" type="rss" xmlUrl="https://news.google.com/rss/topics/CAAqKAgKIiJDQkFTRXdvSkwyMHZNR1ptZHpWbUVnSmxiaG9DUkVVb0FBUAE?hl=de&amp;gl=DE&amp;ceid=DE:de"/>
    <outline title="Schlagzeilen" text="Schlagzeilen" type="rss" xmlUrl="https://news.google.com/rss?hl=de&amp;gl=DE&amp;ceid=DE:de"/>
    <outline title="International" text="International" type="rss" xmlUrl="https://news.google.com/rss/topics/CAAqJggKIiBDQkFTRWdvSUwyMHZNRGx1YlY4U0FtVnVHZ0pFUlNnQVAB?hl=de&amp;gl=DE&amp;ceid=DE:de"/>
    <outline title="Gesundheit" text="Gesundheit" type="rss" xmlUrl="https://news.google.com/rss/topics/CAAqIQgKIhtDQkFTRGdvSUwyMHZNR3QwTlRFU0FtVnVLQUFQAQ?hl=de&amp;gl=DE&amp;ceid=DE:de"/>
    <outline title="Golem.de" text="Golem.de" type="rss" xmlUrl="https://rss.golem.de/rss.php?feed=RSS1.0"/>
    <outline title="Wirtschaft" text="Wirtschaft" type="rss" xmlUrl="https://news.google.com/rss/topics/CAAqJggKIiBDQkFTRWdvSUwyMHZNRGx6TVdZU0FtVnVHZ0pFUlNnQVAB?hl=de&amp;gl=DE&amp;ceid=DE:de"/>
    <outline title="Handelsblatt" text="Handelsblatt" type="rss" xmlUrl="https://www.handelsblatt.com/contentexport/feed/finanzen/"/>
    <outline title="NZZ News – Aktuelle Nachrichten - Neue Zürcher Zeitung" text="NZZ News – Aktuelle Nachrichten - Neue Zürcher Zeitung" type="rss" xmlUrl="https://www.nzz.ch/startseite.rss"/>
    <outline title="SPIEGEL ONLINE - Schlagzeilen" text="SPIEGEL ONLINE - Schlagzeilen" type="rss" xmlUrl="https://www.spiegel.de/schlagzeilen/index.rss"/>
    <outline title="Wirtschaft - Neuigkeiten von der Börse und aus Unternehmen" text="Wirtschaft - Neuigkeiten von der Börse und aus Unternehmen" type="rss" xmlUrl="http://newsfeed.zeit.de/wirtschaft/index"/>
    <outline title="heise online News" text="heise online News" type="rss" xmlUrl="http://www.heise.de/newsticker/heise.rdf"/>
    <outline title="heise Security" text="heise Security" type="rss" xmlUrl="https://www.heise.de/security/rss/news-atom.xml"/>
    <outline title="taz.de - taz.de" text="taz.de - taz.de" type="rss" xmlUrl="https://taz.de/!p4608;rss/"/>
    <outline title="ZEIT ONLINE | Nachrichten, Hintergründe und Debatten" text="ZEIT ONLINE | Nachrichten, Hintergründe und Debatten" type="rss" xmlUrl="http://newsfeed.zeit.de/index"/>
    <outline title="NZZ Digital Nachrichten - News aus der digitalen Welt" text="NZZ Digital Nachrichten - News aus der digitalen Welt" type="rss" xmlUrl="http://www.nzz.ch/aktuell/digital.rss"/>
    <outline title="GameStar - News" text="GameStar - News" type="rss" xmlUrl="https://www.gamestar.de/news/rss/news.rss"/>
    <outline title="Engadget" text="Engadget" type="rss" xmlUrl="https://www.engadget.com/rss-full.xml"/>
    <outline title="SPIEGEL ONLINE - Wirtschaft" text="SPIEGEL ONLINE - Wirtschaft" type="rss" xmlUrl="https://www.spiegel.de/wirtschaft/index.rss"/>
    <outline title="SPIEGEL ONLINE - Gesundheit" text="SPIEGEL ONLINE - Gesundheit" type="rss" xmlUrl="https://www.spiegel.de/gesundheit/index.rss"/>
  </body>
</opml>

**Comment by shuvashish76** [comment] 2024-09-07 08:53
Hello, I'm using Readrops version 2.0-BETA02 from F-Droid.
It doesn't let me pick the opml file exported from [AniVu](https://f-droid.org/packages/com.skyd.anivu/) from my file manager.

```
<?xml version='1.0' encoding='UTF-8' ?>
<opml version="2.0">
  <head>
    <title>AniVu</title>
    <dateCreated>Sat Sep 07 14:16:03 GMT+05:30 2024</dateCreated>
  </head>
  <body>
    <outline htmlUrl="https://f-droid.org/feed.xml" text="F-Droid - Free and Open Source Android App Repository" title="F-Droid - Free and Open Source Android App Repository" xmlUrl="https://f-droid.org/feed.xml" />
    <outline htmlUrl="https://news.nononsenseapps.com/index.atom" text="Feeder News" title="Feeder News" xmlUrl="https://news.nononsenseapps.com/index.atom" />
  </body>
</opml>
```
